USE QuanLyChoThueNha;
GO

/*
  Chuyen cac cot hien thi noi dung tieng Viet sang NVARCHAR de tranh loi dau tieng Viet
  bi bien thanh dau hoi cham. Script nay khong khoi phuc duoc du lieu da bi hong truoc do;
  can nhap/sua lai cac dong da thanh '?' sau khi chay migration.
*/

ALTER TABLE TaiKhoan ALTER COLUMN TenDangNhap NVARCHAR(100) NOT NULL;
ALTER TABLE TaiKhoan ALTER COLUMN MatKhauHash NVARCHAR(255) NOT NULL;
ALTER TABLE TaiKhoan ALTER COLUMN Email NVARCHAR(150) NULL;
ALTER TABLE TaiKhoan ALTER COLUMN VaiTro NVARCHAR(50) NOT NULL;

ALTER TABLE Admin ALTER COLUMN HoTen NVARCHAR(150) NOT NULL;
ALTER TABLE NhanVienQuanLy ALTER COLUMN HoTen NVARCHAR(150) NOT NULL;
ALTER TABLE KhachThue ALTER COLUMN HoTen NVARCHAR(150) NOT NULL;
ALTER TABLE KhachThue ALTER COLUMN DiaChi NVARCHAR(255) NULL;

ALTER TABLE KhuVuc ALTER COLUMN TenKhuVuc NVARCHAR(150) NOT NULL;
ALTER TABLE KhuVuc ALTER COLUMN Quan NVARCHAR(100) NULL;
ALTER TABLE KhuVuc ALTER COLUMN ThanhPho NVARCHAR(100) NULL;

ALTER TABLE LoaiCanHo ALTER COLUMN TenLoai NVARCHAR(100) NOT NULL;
ALTER TABLE LoaiCanHo ALTER COLUMN MoTa NVARCHAR(500) NULL;
ALTER TABLE Toa ALTER COLUMN TenToa NVARCHAR(100) NOT NULL;
ALTER TABLE Toa ALTER COLUMN DiaChi NVARCHAR(255) NULL;
ALTER TABLE Toa ALTER COLUMN MoTa NVARCHAR(500) NULL;

ALTER TABLE CanHo ALTER COLUMN TinhTrang NVARCHAR(50) NOT NULL;
ALTER TABLE CanHo ALTER COLUMN MoTa NVARCHAR(1000) NULL;
ALTER TABLE HinhAnhNha ALTER COLUMN DuongDanAnh NVARCHAR(500) NOT NULL;
ALTER TABLE HinhAnhNha ALTER COLUMN MoTa NVARCHAR(255) NULL;

ALTER TABLE TienNghi ALTER COLUMN TenTienNghi NVARCHAR(100) NOT NULL;
ALTER TABLE TienNghi ALTER COLUMN MoTa NVARCHAR(255) NULL;
ALTER TABLE TienNghiCuaCanHo ALTER COLUMN GhiChu NVARCHAR(255) NULL;

ALTER TABLE PhieuDatTruoc ALTER COLUMN TrangThai NVARCHAR(50) NOT NULL;
ALTER TABLE PhieuDatTruoc ALTER COLUMN PhuongThucThanhToan NVARCHAR(50) NULL;
ALTER TABLE PhieuDatTruoc ALTER COLUMN GhiChu NVARCHAR(500) NULL;

ALTER TABLE HopDong ALTER COLUMN TrangThai NVARCHAR(50) NOT NULL;
ALTER TABLE HopDong ALTER COLUMN GhiChu NVARCHAR(1000) NULL;

ALTER TABLE LoaiHoaDon ALTER COLUMN TenLoai NVARCHAR(100) NOT NULL;
ALTER TABLE LoaiHoaDon ALTER COLUMN MoTa NVARCHAR(255) NULL;
ALTER TABLE HoaDonThanhToan ALTER COLUMN KyThanhToan NVARCHAR(20) NULL;
ALTER TABLE HoaDonThanhToan ALTER COLUMN TrangThai NVARCHAR(50) NOT NULL;
ALTER TABLE HoaDonThanhToan ALTER COLUMN PhuongThucThanhToan NVARCHAR(50) NULL;

ALTER TABLE GiaHanHopDong ALTER COLUMN TrangThai NVARCHAR(50) NOT NULL;
ALTER TABLE PhieuTraNha ALTER COLUMN TinhTrangNha NVARCHAR(500) NULL;
ALTER TABLE PhieuTraNha ALTER COLUMN GhiChu NVARCHAR(500) NULL;
ALTER TABLE PhieuXuLyViPham ALTER COLUMN LoaiViPham NVARCHAR(100) NULL;
ALTER TABLE PhieuXuLyViPham ALTER COLUMN MoTa NVARCHAR(500) NULL;
ALTER TABLE PhieuXuLyViPham ALTER COLUMN TinhTrang NVARCHAR(50) NOT NULL;

PRINT N'Da chuyen cac cot noi dung sang NVARCHAR.';
GO
